### ISSUE TITLE
the scrapyd server port issue

### ISSUE THREAD

**Issue by fightingpjh** [my8100/scrapyd-cluster-on-heroku-scrapyd-app#1]
in this https://github.com/my8100/scrapyd-cluster-on-heroku-scrapyd-app repo, thd init.py file set the scrapyd port 6800 by this:
PORT = int(os.environ.get('PORT', 6800))
with io.open("scrapyd.conf", 'r+', encoding='utf-8') as f:
f.read()
f.write(u'\nhttp_port = %s\n' % PORT)

when i deployed Scrapyd server on heroku.com :
telnet pjhscrapyd1.heroku.com 6800 Failed
telnet pjhscrapyd1.heroku.com 6801 Failed
telnet pjhscrapyd1.heroku.com 80 Succeed

what's wrong with it?

**Comment by my8100** [comment]
https://devcenter.heroku.com/articles/runtime-principles#web-servers
_Each web process simply binds to a port, and listens for requests coming in on that port. The port to bind to is assigned by Heroku as the PORT environment variable._

1. Select an app in https://dashboard.heroku.com/apps
2. More -> Restart all dynos
3. More -> View logs
```
app[web.1]: 2019-04-10T07:34:29+0000 [-] Scrapyd web console available at http://0.0.0.0:59404/
```
